language: python
python:
  - "2.7"
  - "3.5"
cache: pip

install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - flake8 docker_ci_deploy
  - py.test --cov docker_ci_deploy docker_ci_deploy

after_success:
  - codecov

deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: Yc1UKoESBlo8CO3vyzOBJBv1P6IAe6gpX6jR0pm8Xf/ZKSbKojPUljXNy6doUvk2XrC0MlTwa4ucoO8QRJ7W0vR4kjBbfF2N//s4vqqpKWCYkPbAzHFvs28haptsZfBpMcxh2sH0/sgFglihxYClTdNtNStEYaobx5ykZFNsHeipomd62qWC5Alc41BAk4VG/MX20hLnO8mzyI5P7ziyH4lpi7jCFMT5r9bL8ooL2WaifFqP8x/4VRYM+WPxx/+3PVf/JcQTBEH2UXiUTzgh4MYWhrLTF5BY56wzDSl9ovG3cPv/4iZWWnpF4J0lymaV1iqKb9hNQGorFNbZuJIwL0HX+Bp/2ZZpEeg4BmvkBXSgIydXxcbGulYf8P7/aciN8MR5onPZwPEXyBQe9SnuWnGpHxmXqM2lXvbhpRN/FJDT8uCB/y7RILmXcKBikhSiZ/WvnGoExYdDetD5DLtXVX1C7yKDajazNkTeSkZURn9aIDWfdBkZhwkpVNNYbmPSG0vlXiYLavmDzygSvr9s0OLwrVjacLKhQOT/BBHbohq2ihKkg2Pr59RsescNDSAReNMeqhJlyo1fXR9neJcaJPZUGppgjz76ZXHj4IM7kZZh2G3+zjjUgUoji+h61jAfWG1KAtv1rn/lOQa5Zn7u/Hqdo6W1ZoQ7E6h03Nhoya4=
    on:
      tags: true
