language: python
python:
  - "2.7"
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install -r requirements-dev.txt

script:
  - flake8 docker_ci_deploy
  - py.test docker_ci_deploy
